### ISSUE TITLE
qrc中的模块 import 你是如何实现的，为什么我尝试了一直提示 module is not installed

### ISSUE THREAD

**Issue by dongsir** [GDPURJYFS/WellChat#7]
![2410](https://cloud.githubusercontent.com/assets/2283762/15570061/b1462fb2-2366-11e6-956f-b30ff0042f6a.jpg)
我看到你的项目中有R.qml被定义为Resource 1.0
并且在同一个qrc中的Chatpage.qml中通过import Resource 1.0 as R 就能使用。
而我这样子使用就会一直提示module xxx is not installed.

我想知道在自己的一个项目（qml项目）中，封装了一些控件放在了一起（都放在了qrc资源中），也编辑了qmldir。

qrc中的其他qml 想通过import moduleName version 的方式引用而不是现在的这样子只能通过相对路径的方式。
希望能得到你的解答。

**Comment by qyvlik** [comment]
[在qml工程中怎么使用qmldir进行模块管理](http://blog.csdn.net/qyvlik/article/details/44758509)

[qml编程规范--名字（命名规范）](http://blog.csdn.net/qyvlik/article/details/45046253)
